
title: "Portfolio | Lawa Foumsou Prosper"
description: "Élève Ingénieur Statisticien Économiste à l'ENSAE Dakar | Passionné de data science"
author: "Lawa Foumsou Prosper"
email: lawafoum@gmail.com
lang: fr

logo: "/img/profil.jpg"
favicon: "/img/profil.jpg"

theme: jekyll-theme-minimal
show_excerpts: true
title_separator: " | "

show_downloads: true

social_links:
  - name: github
    url: https://github.com/proslawa
  - name: linkedin
    url: https://www.linkedin.com/in/proslawa
  - name: twitter
    url: https://twitter.com/FoumsouLawa02
  - name: email
    url: mailto:lawafoum@gmail.com

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

downloads:
  - name: "CV Lawa Foumsou Prosper"
    url: "/files/CV_Lawa_Foumsou_Prosper.pdf"
    description: "Téléchargez mon CV en PDF"
  - name: "Portfolio PDF"
    url: "/files/Portfolio_Lawa_Foumsou.pdf"
    description: "Téléchargez mon portfolio complet"

