title: "Portfolio | Lawa Foumsou Prosper"
description: "Élève Ingénieur Statisticien Économiste à l'ENSAE Dakar | Passionné de data science, économie et statistiques appliquées"
author: "Lawa Foumsou Prosper"
email: lawafoum@gmail.com

logo: "/img/profil.jpg"

theme: minimal
show_excerpts: true

minima:
  social_links:
    github: https://github.com/proslawa
    linkedin: https://www.linkedin.com/in/proslawa
    twitter: https://twitter.com/FoumsouLawa02
    email: mailto:lawafoum@gmail.com

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

lang: fr
