# -------------------------------
# Configuration principale du site
# -------------------------------
title: "Portfolio | Lawa Foumsou Prosper"
description: "Élève Ingénieur Statisticien Économiste à l'ENSAE Dakar"
show_downloads: true
author: "Lawa Foumsou Prosper"
email: lawafoum@gmail.com
lang: fr

# Logo et favicon
logo: "/img/profil.jpg"
favicon: "/img/profil.jpg"

# Thème et affichage
theme: jekyll-theme-minimal
show_excerpts: true
title_separator: " | "

# -------------------------------
# Réseaux sociaux
# -------------------------------
social_links:
  - name: github
    url: https://github.com/proslawa
  - name: linkedin
    url: https://www.linkedin.com/in/proslawa
  - name: twitter
    url: https://twitter.com/FoumsouLawa02
  - name: email
    url: mailto:lawafoum@gmail.com

# -------------------------------
# Plugins
# -------------------------------
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# -------------------------------
# Markdown
# -------------------------------
markdown: kramdown

# -------------------------------
# Autres options possibles
# -------------------------------
# Permet de ne pas générer les pages inutiles
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

